### Numpy module

NumPy is a fundamental library for scientific computing in python. It provides support for array and matrices

and methods to perform different mathameticals operations on them

In [1]:
import numpy as np

In [56]:
arr1 = np.array([1,2,3,4,5])  ## creating a array of single dimension and we donot provide rows and coloumns there
                              ## this is different from list
print(arr1)
print(type(arr1))
print(arr1.shape)  ## provide the shape
print(arr1.ndim)  ## provide the dimension

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1


In [13]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## this now becomes a 2d array but with one row 

array([[1, 2, 3, 4, 5]])

In [19]:
arr2 = np.array([[1,2,3,4],[2,3,4,5]]) ## matrix
print(arr2)
print(arr2.shape)
arr2.reshape(4,2)

[[1 2 3 4]
 [2 3 4 5]]
(2, 4)


array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 5]])

In [24]:
mat = np.zeros((3,3)) #similarly using np.ones we can create matrix containing only one
print(mat)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


creating identity matrix

In [57]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.eye(3,5)  ## not identity matrix but some time required

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

### NumPy vectorize operations:

In [31]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,3,4,5,6])

## addition
print("addition",arr1+arr2)

##substraction
print("substraction ",arr1-arr2)

##multiplication

print("multiplication ",arr1*arr2)


addition [ 3  5  7  9 11]
substraction  [-1 -1 -1 -1 -1]
multiplication  [ 2  6 12 20 30]


In [34]:
print(np.sqrt(arr1))
print(np.exp(arr1)) 
print(np.sin(arr1))
print(np.log(arr1))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


### Slicing

In [36]:
mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
## accesing single element is similar like accesing a 2d array
print(mat[0][1])

2


In [45]:
## to access a sub matrix we use slicing
sm1 = mat[1:,2:]  ## tat is we take row from 1 to end and col from 2 to end
print(sm1)
sm2 = mat[1:,1:3]
print(sm2)

[[ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]


there are also statistical functions like mean,variance,std,normalisation

In [54]:
##logical operations

data = np.array([1,2,3,4,5])
print(data%2==0)   ## this will try for all the data points inside array and check the condition

## now to retrive the data satisfying the condition we use

print(data[data%2==0]) ##we can add many conditions

print(data[(data%2==0) & (data>3)])
print(data[(data%2==0) | (data>3)])

[False  True False  True False]
[2 4]
[4]
[2 4 5]
